# Generated by Django 3.1 on 2020-08-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=200)),
                ('budget', models.FloatField()),
            ],
        ),
    ]
