# Generated by Django 3.1.1 on 2020-09-16 15:16
# pylint: skip-file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityId', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('placeId', models.AutoField(primary_key=True, serialize=False)),
                ('placeName', models.CharField(max_length=200)),
                ('timeVisit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tagName', models.CharField(choices=[('cv19', 'Covid-19 Warning Zone'), ('ind', 'Indoors'), ('pop', 'Popular'), ('safe', 'Safe Place to Visit during Covid')], max_length=10)),
                ('tagID', models.Field(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('tripId', models.AutoField(primary_key=True, serialize=False)),
                ('tripName', models.CharField(max_length=200)),
                ('transMode', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('sub', 'Subway'), ('fly', 'Flight')], max_length=5)),
                ('noPeopleTrip', models.IntegerField()),
                ('tripType', models.CharField(choices=[('advt', 'Adventurous'), ('kd', 'Kid-Friendly'), ('relax', 'Relaxing')], max_length=10)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('sourceCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripHome.city')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('placeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripHome.places')),
                ('tripId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripHome.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Tagged_as',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripHome.places')),
                ('tagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripHome.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripHome.city')),
                ('tripId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripHome.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Contains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripHome.city')),
                ('placeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripHome.places')),
            ],
        ),
    ]
